### ISSUE TITLE
css animation 绕方块旋转动画效果

### ISSUE THREAD

**Issue by LoeiFy** [LoeiFy/Recordum#8]
一个比较好玩的动画效果，具体代码：
### HTML

``` html
<div id="container">
    <li>
        <a href="#"></a>
    </li>
    <li>
        <a href="#"></a>
    </li>
    ...
    <li>
        <a href="#"></a>
    </li>
</div>
```
### CSS

``` css
#container {
    background: #000;
}
#container li {
    width: 100px;
    height: 100px;
    padding: 1px;
    display: inline-block;
    vertical-align: top;
    position: relative;
}
#container a {
    display: block;
    width: 100px;
    height: 100px;
}
#container a:before, #container a:after {
    content: '';
    position: absolute;
    background: blue;
    height: 1px;
    z-index: 3;
}
#container li a:before {
    -webkit-animation: rounda 2s linear forwards infinite;
    top: 0;
    left: 0;
}
#container li a:after {
    -webkit-animation: rounda 2s 1s linear forwards infinite;
    bottom: 0;
    right: 0;
}


#container li:before, #container li:after {
    content: '';
    position: absolute;
    background: blue;
    width: 1px;
    z-index: 3;
}
#container li:before {
    -webkit-animation: roundb 2s 0.5s linear forwards infinite;
    right: 0;
    top: 0;
}
#container li.animate:after {
    -webkit-animation: roundb 2s 1.5s linear forwards infinite;
    left: 0;
    bottom: 0;
}

@-webkit-keyframes rounda {
  0% {
      width: 0;
  }

  25% {
      width: 100%;
  }

  50% {
      width: 100%;
  }

  50.1% {
      width: 0;
  }
}
@-webkit-keyframes roundb {
  0% {
      height: 0;
  }

  25% {
      height: 100%;
  }

  50% {
      height: 100%;
  }

  50.1% {
      height: 0;
  }
}
```
### DEMO

http://jsfiddle.net/am0200/x9u4w12x/
这里是针对 webkit 的动画，Firefox 之类的代码需要另外加，所以请使用 webkit 浏览器
### 说明

当页面多个这样动画运行时候，效果蛮不错，当然 MacBook 发热开始了
